---
title: "Title"
output:
  html_document:
    css: ~/GitHub/RADC/libs/css/sidebar.css
    keep_md: yes
    toc: yes
---

<!-- These two chunks should be added in the beginning of every .Rmd that you want to source an .R script -->
<!--  The 1st mandatory chunck  -->
<!--  Set the working directory to the repository's base directory -->
```{r, echo=F, message=F} 
#Don't combine this call with any other chunk 
# cat("Working directory: ", getwd()) # check where you are
  library(knitr)
# Rmd is in "./reports/reportA/reportA.Rmd", but now the root is "./"
  knitr::opts_knit$set(root.dir='../../') 
```

<!--  The 2nd mandatory chunck  -->
<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=F}
# set options shared by all chunks
opts_chunk$set(
  results='show', 
  message = TRUE,
  comment = NA, 
  tidy = FALSE,
  # fig.height = 4, 
  # fig.width = 5.5, 
  # out.width = "900px",
  fig.path = 'figure_rmd/',     
  dev = "png",
  dpi = 300
  # fig.path = 'figure_pdf/',     
  # dev = "pdf"#,
  # dev.args=list(pdf = list(colormodel = 'cmyk'))
)
echoChunks <- FALSE
options(width=120) #So the output is 50% wider than the default.
# connect to the file with the underlying R script  
read_chunk("./reports/kb_profiles/kb_profiles.R") 
```




```{r load_packages, echo=echoChunks, message=FALSE}
```

```{r load_paths, echo=echoChunks, results='show', message=FALSE}
```

<!-- Load 'sourced' R files. --> 
```{r load_scripts, echo=echoChunks, results='show', message=FALSE}
```

<!-- Load the sources.  Suppress the output when loading sources. --> 
```{r load_sources, echo=echoChunks, message=FALSE}
```

<!-- Load any Global functions and variables declared in the R file --> 
```{r declare_globals, echo=echoChunks, results='show', message=FALSE}
```

<!-- Load the datasets.   -->
```{r load_data, echo=echoChunks, results='show', message=FALSE}
```

<!-- Tweak the datasets.   -->
```{r tweak_data, echo=echoChunks, results='show', message=FALSE}
```

<!-- Basic table view.   -->
```{r basic_table, echo=TRUE, results='show', message=FALSE}
```

## 1 
```{r grip_bnt, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```

## 2
```{r grip_bostonstorydelay, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```


## 3 
```{r grip_bostonstoryimm, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```


##  4 Grip <-> Categories
```{r grip_categories, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```

## 5 
```{r grip_complexidea, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```

## 6 
```{r grip_digitordering, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```

## 7 
```{r grip_digitsb, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```

## 8 
```{r grip_digitsf, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```


## 9 Grip <-> Digit Symbols
```{r grip_digitsymbol, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```

## 10
```{r grip_lineorientation, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```

## 11
```{r grip_lmdelayed, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```

## 12
```{r grip_lmimmed, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```

## 13 
```{r grip_matrices, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```

## 14 Grip <-> MMSE 
```{r grip_mmse, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```


## 15 
```{r grip_numbercomp, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```

## 16  Grip <-> Word List Immediate
```{r grip_wordlistimmed, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```

## 17 Grip <-> Word List Delayed
```{r grip_wordlistdelayed, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```

## 18 
```{r grip_wordlistrec, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```








## FEV <-> Categories
```{r fev_categories, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```

## FEV <-> Digit Symbols
```{r fev_digitsymbol, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```

## FEV <-> Word List Im
```{r fev_wordlistimmed, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```

## FEV <-> MMSE 
```{r fev_mmse, echo=echoChunks, results='hold', message=FALSE, fig.width=10, fig.height=10}
```


